steps:
  # Frontend Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/frontend:latest']
    allowFailure: true

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/frontend:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/frontend:latest',
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      '-f', 'Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NODE_ENV=production,BASE_URL=https://platform.dcisionai.com'
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest,OPENAI_API_KEY=openai-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_ANON_KEY=supabase-anon-key:latest,SUPABASE_SERVICE_KEY=supabase-service-key:latest'

  # Solver Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/solver:latest']
    allowFailure: true

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/solver:$SHORT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/solver:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/solver:latest',
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      '-f', 'solver/Dockerfile',
      'solver/'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/solver:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/solver:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'solver'
      - '--image'
      - 'gcr.io/$PROJECT_ID/solver:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'

  # Data Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/data:latest']
    allowFailure: true

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/data:$SHORT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/data:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/data:latest',
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      '-f', 'data/Dockerfile',
      'data/'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/data:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/data:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'data'
      - '--image'
      - 'gcr.io/$PROJECT_ID/data:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'

  # Map domains to services
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service'
      - 'frontend'
      - '--domain'
      - 'platform.dcisionai.com'
      - '--region'
      - '${_REGION}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service'
      - 'solver'
      - '--domain'
      - 'solve.dcisionai.com'
      - '--region'
      - '${_REGION}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service'
      - 'data'
      - '--domain'
      - 'data.dcisionai.com'
      - '--region'
      - '${_REGION}'

images:
  - 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/frontend:latest'
  - 'gcr.io/$PROJECT_ID/solver:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/solver:latest'
  - 'gcr.io/$PROJECT_ID/data:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/data:latest'

substitutions:
  _REGION: us-central1

options:
  machineType: 'E2_HIGHCPU_8' 