steps:
  # Frontend Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/dcisionai/frontend:latest']
    allowFailure: true


  # Generate .env.production for Next.js build (build-time env vars)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "NEXT_PUBLIC_SUPABASE_URL=$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_SUPABASE_URL --project=$PROJECT_ID)" > .env.production
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_SUPABASE_ANON_KEY --project=$PROJECT_ID)" >> .env.production

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--progress=plain',
      '--no-cache',
      '-t', 'gcr.io/dcisionai/frontend:latest',
      '-f', './Dockerfile',
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dcisionai/frontend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy frontend \
          --image gcr.io/dcisionai/frontend:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars NEXT_PUBLIC_SUPABASE_URL=$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_SUPABASE_URL),NEXT_PUBLIC_SUPABASE_ANON_KEY=$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_SUPABASE_ANON_KEY),AIRBYTE_API_URL=https://data.dcisionai.com

  # Map domain to frontend service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta run domain-mappings create \
          --service frontend \
          --domain platform.dcisionai.com \
          --region us-central1 \
        || echo "Domain mapping exists or failed; continuing..."

images:
  - 'gcr.io/dcisionai/frontend:latest'

options:
  machineType: 'E2_HIGHCPU_32'
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: 'docker-cache'
      path: '/docker-cache'
