steps:
  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/dcisionai-frontend:latest'
      - '--target'
      - 'production'
      - '.'

  # Push frontend image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/dcisionai-frontend:latest'

  # Deploy frontend with proper environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dcisionai-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dcisionai-frontend:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,SUPABASE_URL=${_SUPABASE_URL},SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY},ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/dcisionai-frontend:latest'

substitutions:
  _SUPABASE_URL: 'your-supabase-url'
  _SUPABASE_ANON_KEY: 'your-supabase-anon-key'
  _ANTHROPIC_API_KEY: 'your-anthropic-api-key' 