steps:
  # Build Solver Service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--progress=plain',
      '--no-cache',
      '-t', 'gcr.io/dcisionai/solver:latest',
      '-f', './solver-service/Dockerfile',
      './solver-service'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dcisionai/solver:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy solver \
          --image gcr.io/dcisionai/solver:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars SUPABASE_URL=$(gcloud secrets versions access latest --secret=supabase-url),SUPABASE_SERVICE_KEY=$(gcloud secrets versions access latest --secret=supabase-service-key)

  # Build Data Service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/dcisionai/data:latest',
      '-f', './airbyte-service/Dockerfile',
      './airbyte-service'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dcisionai/data:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy data \
          --image gcr.io/dcisionai/data:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars SUPABASE_URL=$(gcloud secrets versions access latest --secret=supabase-url),SUPABASE_SERVICE_KEY=$(gcloud secrets versions access latest --secret=supabase-service-key)

  # Map domains
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service'
      - 'solver'
      - '--domain'
      - 'solve.dcisionai.com'
      - '--region'
      - 'us-central1'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service'
      - 'data'
      - '--domain'
      - 'data.dcisionai.com'
      - '--region'
      - 'us-central1'

images:
  - 'gcr.io/dcisionai/solver:latest'
  - 'gcr.io/dcisionai/data:latest'

options:
  machineType: 'E2_HIGHCPU_32'
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: 'docker-cache'
      path: '/docker-cache' 