version: '3.8'

services:
  plugin-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=8002
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run dev 