options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build and deploy solver service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/solver-service:latest', './solver-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/solver-service:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'solver-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/solver-service:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,PLUGIN_SERVICE_URL=${_PLUGIN_SERVICE_URL}'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'

  # Build and deploy plugin service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/plugin-service:latest', './plugin-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/plugin-service:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'plugin-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/plugin-service:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,SOLVER_SERVICE_URL=${_SOLVER_SERVICE_URL}'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'

  # Build and deploy frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,PLUGIN_SERVICE_URL=${_PLUGIN_SERVICE_URL},SOLVER_SERVICE_URL=${_SOLVER_SERVICE_URL}'
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest,OPENAI_API_KEY=openai-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_ANON_KEY=supabase-anon-key:latest,SUPABASE_SERVICE_KEY=supabase-service-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/solver-service:latest'
  - 'gcr.io/$PROJECT_ID/plugin-service:latest'
  - 'gcr.io/$PROJECT_ID/frontend:latest'

substitutions:
  _REGION: us-central1
  _SOLVER_SERVICE_URL: https://solver-service-${_REGION}-${PROJECT_ID}.a.run.app
  _PLUGIN_SERVICE_URL: https://plugin-service-${_REGION}-${PROJECT_ID}.a.run.app

timeout: 3600s 