steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NODE_ENV=production,BASE_URL=${_BASE_URL},ORTOOLS_SERVICE_URL=${_SOLVER_SERVICE_URL},PLUGIN_SERVICE_URL=${_PLUGIN_SERVICE_URL}'
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest,OPENAI_API_KEY=openai-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_ANON_KEY=supabase-anon-key:latest,SUPABASE_SERVICE_KEY=supabase-service-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'

substitutions:
  _REGION: us-central1
  _BASE_URL: https://app.dcisionai.com
  _SOLVER_SERVICE_URL: https://solver-service-${_REGION}-${PROJECT_ID}.a.run.app
  _PLUGIN_SERVICE_URL: https://plugin-service-${_REGION}-${PROJECT_ID}.a.run.app 