name: Deploy Backend Services

on:
  push:
    branches: [ main ]
    paths:
      - 'plugin-service/**'
      - 'solver-service/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'plugin-service/**'
      - 'solver-service/**'
      - '.github/workflows/deploy.yml'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  deploy-plugin-service:
    name: Deploy Plugin Service
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'plugin-service/') || contains(github.event.head_commit.added, 'plugin-service/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Deploy Plugin Service
        working-directory: ./plugin-service
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions=COMMIT_SHA=${{ github.sha }}

  deploy-solver-service:
    name: Deploy Solver Service
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'solver-service/') || contains(github.event.head_commit.added, 'solver-service/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Deploy Solver Service
        working-directory: ./solver-service
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions=COMMIT_SHA=${{ github.sha }} 